CREATE TABLE IF NOT EXISTS  PRODUCT_TYPE (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_type VARCHAR(50)

);

CREATE TABLE IF NOT EXISTS  PRODUCT (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(250),
    type_id BIGINT,
    price DECIMAL(19,2),
    FOREIGN KEY(type_id) REFERENCES PRODUCT_TYPE(id)

);

CREATE TABLE IF NOT EXISTS DISCOUNT (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type_id BIGINT,
    percent INTEGER,
    FOREIGN KEY(type_id) REFERENCES PRODUCT_TYPE(id)

);

CREATE TABLE IF NOT EXISTS  VISIT_COUNTER(

    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT,
    visit_counter BIGINT,
    FOREIGN KEY(product_id) REFERENCES PRODUCT(id)

);
